package com.example.aims.exception;

public enum PaymentErrorCode {
    CONFIG_INCOMPLETE,
    ORDER_NOT_FOUND,
    ORDER_NOT_PENDING_PAYMENT,
    INVOICE_MISSING,
    INVOICE_AMOUNT_MISSING,
    DUPLICATE_TRANSACTION,
    CAPTURE_FAILED,
    REFUND_AMOUNT_INVALID,
    REFUND_CAPTURE_ID_MISSING,
    GATEWAY_UNAVAILABLE,
    GATEWAY_RESPONSE_UNEXPECTED,
    RETRY_INTERRUPTED,
    UNSUPPORTED_PAYMENT_METHOD
}