services:
  postgres-db:
    image: postgres:17
    container_name: aims-postgres
    restart: unless-stopped
    ports:
      - "5435:5432"
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
      TZ: ${TZ:-Asia/Ho_Chi_Minh}
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
