import {
  AppstoreOutline,
  AuditOutline,
  CheckOutline,
  CloseOutline,
  EyeOutline,
  FacebookFill,
  HistoryOutline,
  HomeOutline,
  InstagramOutline,
  LockOutline,
  MailOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  ReloadOutline,
  SearchOutline,
  TagOutline,
  TwitterOutline,
  UserOutline,
} from '@ant-design/icons-angular/icons';

export const appIcons = [
  MailOutline,
  LockOutline,
  FacebookFill,
  InstagramOutline,
  TwitterOutline,
  MenuFoldOutline,
  MenuUnfoldOutline,
  HomeOutline,
  AppstoreOutline,
  AuditOutline,
  CheckOutline,
  CloseOutline,
  EyeOutline,
  HistoryOutline,
  ReloadOutline,
  SearchOutline,
  TagOutline,
  UserOutline,
];
